# Basic Azure DevOps pipeline to invoke the automation using Azure DevOps pipeline.",
trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: InvokeAutomation
    jobs:
      - job: "InvokeAutomationScript"
        displayName: "Invoke Automation Script"
        steps:
          - task: PowerShell@2
            displayName: "Invoke Powershell Script"
            inputs:
              filePath: "./scripts/RunExamplesStandalone.ps1"
              failOnStderr: true",
              pwsh: true"
